// See https://aka.ms/new-console-template for more information


Console.WriteLine();
Console.WriteLine("Practice number sizes and ranges");
Console.WriteLine("Q1. FizzBuzz");

for (int i = 1; i < 101; i++)
{
    if (i % 3 == 0 && i % 5 != 0)
    {
        Console.WriteLine("fizz");
    }
    else if (i % 3 != 0 && i % 5 == 0)
    {
        Console.WriteLine("buzz");
    }
    else if (i % 3 == 0 && i % 5 == 0)
    {
        Console.WriteLine("fizzbuzz");
    }
    else
    {
        Console.WriteLine(i);
    }
}

Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q1. Extension");

int max = 500;
for (byte i = 0; i < max; i++)
{
    if (Byte.MaxValue < max)
    {
        Console.WriteLine("Warning: Byte overflow will occur!");
        break;
    }
    
    Console.WriteLine(i);
}


Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q1. Extension");

int correctNumber = new Random().Next(3) + 1;
Console.WriteLine("A random number is generated by the system between 1 and 3!!");

Console.WriteLine("Guess the number: ");
int guessedNumber = int.Parse(Console.ReadLine());


switch (guessedNumber)
{
    case 1:
        if (correctNumber > 1)
        {
            Console.WriteLine("Guessed number is lower than the generated number");
        }
        else
        {
            Console.WriteLine("Your guess is correct!!");
        }

        break;
    
    case 2: 
        if (correctNumber > 2)
        {
            Console.WriteLine("Guessed number is lower than the generated number");
        }
        else if (correctNumber < 2)
        {
            Console.WriteLine("Guessed number is higher than the generated number");
        }
        else
        {
            Console.WriteLine("Your guess is correct!!");
        }

        break;
    case 3: 
        if (correctNumber < 3)
        {
            Console.WriteLine("Guessed number is higher than the generated number");
        }
        else
        {
            Console.WriteLine("Your guess is correct!!");
        }

        break;
    
    default: Console.WriteLine("Your Guess is out of range (less than 1 or more than 3)");
        break;
        
}


Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q2. Printing Pyramid");

Console.WriteLine("Enter the number of rows");
int rows = int.Parse(Console.ReadLine());

int mid = (int)Math.Floor((double)(((rows*2)-1)/2));


for (int i = 1; i <= rows; i++)
{
    int low = mid - (i - 1);
    int high = mid + (i - 1);
    
    for (int j = 0; j < (rows * 2) - 1; j++)
    {
        if (j >= low && j <= high)
        {
            Console.Write("*");
        }
        else
        {
            Console.Write(" ");
        }
        
    }
    Console.WriteLine();
}

Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q3 was similar to Q1");
Console.WriteLine("Q4. Age Calculator");

Console.WriteLine("Age Calculator");
DateTime birthDate = new DateTime(2000, 5, 10); 
TimeSpan  Days= DateTime.Today - birthDate;
double ageInDays = Days.TotalDays;
Console.WriteLine("You are "+ ageInDays+ " days old.");

double daysToNextAnniversary = 10000 - (ageInDays % 10000);
DateTime nextdate = DateTime.Today.AddDays(daysToNextAnniversary);
Console.WriteLine($"Your next 10,000-day anniversary will be on: {nextdate}");



Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q5. Automatic Wisher");


DateTime currentTime = DateTime.Now;
Console.WriteLine(currentTime);

if (currentTime.Hour < 12 && currentTime.Hour>6)
{
    Console.WriteLine("Good Morning");
}
else if (currentTime.Hour < 18 && currentTime.Hour>12)
{
    Console.WriteLine("Good Afternoon");
}
else if (currentTime.Hour < 21 && currentTime.Hour>18)
{
    Console.WriteLine("Good Evening");
}
else
{
    Console.WriteLine("Good Night");
}



Console.WriteLine("---------------------------------------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Q6. Printing Pattern");

for (int i = 1; i <= 4; i++)
{
    for (int j = 0; j <= 24; j += i)
    {
        if (j == 24)
        {
            Console.Write(j);
        }
        else
        {
            Console.Write(j+",");
        }
        
    }
    Console.WriteLine();
}

















